export const actionTypes = {
  UPDATE_PROGRAM_DETAILS: 'UPDATE_PROGRAM_DETAILS',
  ADD_WORKOUT: 'ADD_WORKOUT',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  DELETE_WORKOUT: 'DELETE_WORKOUT',
  SET_ACTIVE_WORKOUT: 'SET_ACTIVE_WORKOUT',
  ADD_EXERCISE: 'ADD_EXERCISE',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',
  DELETE_EXERCISE: 'DELETE_EXERCISE',
  ADD_SET: 'ADD_SET',
  UPDATE_SET: 'UPDATE_SET',
  DELETE_SET: 'DELETE_SET',
  CLEAR_STATE: 'CLEAR_STATE'
};
