export const actionTypes = {
  ADD_PROGRAM: 'ADD_PROGRAM',
  DELETE_PROGRAM: 'DELETE_PROGRAM',
  ADD_WORKOUT: 'ADD_WORKOUT',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  DELETE_WORKOUT: 'DELETE_WORKOUT',
  SET_ACTIVE_WORKOUT: 'SET_ACTIVE_WORKOUT',
  ADD_EXERCISE: 'ADD_EXERCISE',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',
  DELETE_EXERCISE: 'DELETE_EXERCISE',
  ADD_SET: 'ADD_SET',
  UPDATE_SET: 'UPDATE_SET',
  DELETE_SET: 'DELETE_SET',
  CLEAR_STATE: 'CLEAR_STATE',
  SAVE_PROGRAM_START: 'SAVE_PROGRAM_START',
  SAVE_PROGRAM_SUCCESS: 'SAVE_PROGRAM_SUCCESS',
  SAVE_PROGRAM_FAILURE: 'SAVE_PROGRAM_FAILURE'
};
